version: '3.3'

services:
   
  api:
    build: .
    command: bundle exec grape server '0.0.0.0'
    volumes:
      - .:/user/src/app
    ports:
      - "9292:9292"
volumes:
    pg_data:
      driver: local
    es_data:
      driver: local
