version: '3.3'

services:
  pg:
    image: postgres:10
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    image: redis
    ports:
      - 6379:6379
   
  # api:
  #   build: .
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #   volumes:
  #     - .:/user/src/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - pg
  #     - es
  #     - redis
volumes:
    pg_data:
      driver: local
    es_data:
      driver: local
